name: Destroy infrastructure
on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: self-hosted
    steps:
      - name: Clone repo 
        uses: actions/checkout@v6

      - name: Copy required secrets 
        run: |
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > terraform/ssh_id.pub
          
      - name: Init tofu
        run: tofu -chdir=terraform init 

      - name: Destroy cluster 
        run: tofu -chdir=terraform destroy -auto-approve
      