---
- name: Set control plane
  hosts: control_plane
  become: true
  vars:
    cidr: 10.244.0.0/16 # Flannel req
    flannel_yaml: "https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml"

  tasks:
    - name: Check if cluster already exists
      stat: 
        path: /etc/kubernetes/admin.conf 
      register: already_exists

    - name: Initialize cluster
      command: |
        kubeadm init --pod-network-cidr={{ cidr }} --control-plane-endpoint={{ ansible_host }}
      when: not already_exists.stat.exists

    - name: Create home directory 
      file:
        path: /home/ubuntu/.kube
        state: directory 
        owner: ubuntu
        group: ubuntu
        mode: '0755'

    - name: Copy config file 
      copy:
        src: /etc/kubernetes/admin.conf 
        dest: /home/ubuntu/.kube/config 
        owner: ubuntu 
        group: ubuntu
        remote_src: true
        mode: '0600'
    
    - name: Install Flannel 
      become: false
      command: kubectl apply -f {{ flannel_yaml }}

    - name: Save output of join command
      command: kubeadm token create --print-join-command
      register: join_command

- name: Make workers join cluster 
  hosts: workers
  become: true
  tasks:  
    - name: Check if workers already joined 
      stat:
        path: /etc/kubernetes/kubelet.conf 
      register: already_joined
    
    - name: Join cluster 
      command: "{{ hostvars['control_plane']['join_command'].stdout }}"
      when: not already_joined.stat.exists
      
- name: Install metrics server and ingress on cluster
  hosts: control_plane
  become: false
  vars:
    metrics_yaml: "https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml"
    ingress_yaml: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/baremetal/deploy.yaml"
  tasks:
    - name: Wait for workers to be ready 
      command: kubectl get nodes
      register: nodes_output
      until: nodes_output.stdout_lines | select('search', 'NotReady') | list | length == 0
      retries: 20
      delay: 15

    - name: Install metrics server
      command: kubectl apply -f {{ metrics_yaml }}

    - name: Patch metrics server
      command: |
        kubectl patch deployment metrics-server -n kube-system \
        --type='json' \
        -p='[{"op": "add", "path": "/spec/template/spec/containers/0/args/-", "value": "--kubelet-insecure-tls"}]' 

    - name: Wait rollout of metrics server
      command: kubectl rollout status deployment/metrics-server -n kube-system --timeout=120s

    - name: Install ingress component
      command: kubectl apply -f {{ ingress_yaml }}

    - name: Wait for install
      command: sleep 10

    - name: Patch ingress to force NodePort to 30080
      command: |
        kubectl patch svc ingress-nginx-controller \
        -n ingress-nginx --type=json \
        -p='[{"op":"replace","path":"/spec/ports/0/nodePort","value":30080}]'
    
    - name: Wait for rollout
      command: |
        kubectl wait \
        --namespace ingress-nginx \
        --for=condition=ready pod \
        --selector=app.kubernetes.io/component=controller \
        --timeout=120s

    - name: Save kubeconfig file in local host
      fetch:
        src: /home/ubuntu/.kube/config
        dest: ~/tofu-gen/kubeconfig
        flat: yes